// <auto-generated />
using System;
using EmployeeDocumentation.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmployeeDocumentation.Migrations
{
    [DbContext(typeof(TeamContext))]
    [Migration("20210403181305_ComplexDataModel")]
    partial class ComplexDataModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EmployeeDocumentation.Models.Documentation", b =>
                {
                    b.Property<int>("DocumentationID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuthorInitials")
                        .HasMaxLength(10);

                    b.Property<int>("Category");

                    b.Property<DateTime>("Date");

                    b.Property<int>("EmployeeID");

                    b.Property<string>("Entry");

                    b.HasKey("DocumentationID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("Documentation");
                });

            modelBuilder.Entity("EmployeeDocumentation.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeID");

                    b.Property<int>("Extension");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50);

                    b.Property<DateTime>("HireDate");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("SupervisorID");

                    b.HasKey("EmployeeID");

                    b.HasIndex("SupervisorID");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("EmployeeDocumentation.Models.Supervisor", b =>
                {
                    b.Property<int>("SupervisorID");

                    b.Property<int>("Extension");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("SupervisorID");

                    b.ToTable("Supervisor");
                });

            modelBuilder.Entity("EmployeeDocumentation.Models.Documentation", b =>
                {
                    b.HasOne("EmployeeDocumentation.Models.Employee", "Employee")
                        .WithMany("Documentation")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EmployeeDocumentation.Models.Employee", b =>
                {
                    b.HasOne("EmployeeDocumentation.Models.Supervisor")
                        .WithMany("Employees")
                        .HasForeignKey("SupervisorID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
